name: va_prod
env_file: .env

networks: { va_net: {} }
volumes:
  va_dbdata:
    external: true
  va_chromadata:            # même volume Chroma (persistant et partagé)
    external: true

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - va_dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [va_net]

  api:
    build:
      context: ./outil_veille_api
      dockerfile: Dockerfile.api
    environment:
      NODE_ENV: production
      PORT: ${API_PORT}
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
    depends_on: { db: { condition: service_healthy } }
    expose: ["${API_PORT}"]
    networks: [va_net]

  nginx:
    image: nginx:alpine
    depends_on: { api: { condition: service_started } }
    ports: ["${NGINX_PORT}:80"]
    volumes:
      - ./_deploy/app-dist:/usr/share/nginx/html:ro
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [va_net]

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: va_chroma
    restart: unless-stopped
    command: ["chroma", "run", "--host", "0.0.0.0", "--port", "8001", "--path", "/data"]
    volumes:
      - va_chromadata:/data
    expose:
      - "8001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8001/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [va_net]