services:
  mysql:
    platform: linux/arm64/v8
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password","--innodb_flush_log_at_trx_commit=2"]
    volumes: 
      - va_mysql_data_dev:/var/lib/mysql
      - ./_db:/docker-entrypoint-initdb.d:ro
    ports:
    - "3306:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 10

  # chroma:
  #   platform: linux/amd64
  #   image: ghcr.io/chroma-core/chroma:latest
  #   environment:
  #     - IS_PERSISTENT=TRUE
  #   volumes:
  #     - va_chroma_data_dev:/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/api/v1/heartbeat || exit 1"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 30

  api:
    build:
      context: ./outil_veille_api
      dockerfile: Dockerfile.api
      target: production
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      NODE_ENV: development
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./outil_veille_api/src:/app/src
      - ./outil_veille_api/routes:/app/routes
      - ./outil_veille_api/services:/app/services
      - ./outil_veille_api/config:/app/config

  front:
    platform: linux/arm64/v8
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./outil_veille_app:/app
    environment:
      VITE_PUBLIC_API_URL: http://localhost:8000
    command: sh -c "npm ci || npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  va_mysql_data_dev:
  # va_chroma_data_dev:
